version: '3'

services:
  mysqldb:
    image: mysql:8.0.26
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_DATABASE=backend_challenge
      - TZ=America/Brasilia
    ports:
      - 3306:3306
    volumes:
      - ./mysqldocker/schema-mysql.sql:/docker-entrypoint-initdb.d/schema-mysql.sql

