version: '3'

services:
  mysqldb:
    image: mysql:8.0.26
    environment:
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_DATABASE=backend_challenge
    ports:
      - 3306:3306
    networks:
      - spring-cloud-network
    volumes:
      - db:/var/lib/mysql
      - /mysqldocker/schema-mysql.sql:/docker-entrypoint-initdb.d/schema-mysql.sql
      - db:/var/lib/mysql
volumes:
  db:
networks:
  spring-cloud-network:
    driver: bridge